pipeline {
    agent any
       tools {
        maven 'maven-3.9.0'
        }

     stages {
        stage('Build') {
            steps {
               sh 'mvn clean install'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }

        stage('Deploy') {
            // when {
            //     branch 'development'
            // }
            steps {
                echo "Running App.java.... on ${BRANCH_NAME}"
                sh 'java src/main/java/com/example/App.java'
            }
        }

        // stage('Deploy') {
        //     steps {
        //         echo 'Running App.java....'
        //         // sh 'javac src/main/java/com/example/App.java'
        //         sh 'java src/main/java/com/example/App.java'
        //     }
        // }


        stage('Archiveartifact') {
            steps {
                archiveArtifacts artifacts: '**/target/*.jar', allowEmptyArchive: true
            }
        }
        

    }

    post {
        // always {
        //     // Steps that always run after the pipeline finishes
        //     echo 'Cleaning up...'
        //     sh 'make clean'
        // }
        success {
            // Steps that run only if the pipeline succeeds
            echo 'Pipeline succeeded!'
        }
        failure {
            // Steps that run only if the pipeline fails
            echo 'Pipeline failed!'
        }
    }
 
}
